### ISSUE TITLE
Поддержка @angular/common 9.1.13

### ISSUE THREAD

**Issue by AlexanderYAntonov** [FriOne/ng-yandex-metrika#19]
В проекте установлена ng-yandex-metrika@4.0.0
Пытаюсь обновить проект с @angular/common@8.2.14 до @angular/common@9.1.13 через 
ng-update @angular/core@9 @angular/cli@9
получаю следующую ошибку
Package "ng-yandex-metrika" has an incompatible peer dependency to "@angular/common" (requires "^7.2.0" (extended), would install "9.1.13").
Package "ng-yandex-metrika" has an incompatible peer dependency to "@angular/core" (requires "^7.2.0" (extended), would install "9.1.13").
Есть ли какая-то версия ng-yandex-metrika, поддерживающая @angular/common@9.1.13 ?

**Comment by trueflywood** [comment]
Ангуляр уже 12 версии. а либа так и не обновляется. Когда ждать обновления?

**Comment by FriOne** [comment]
@AlexanderYAntonov обновил до последней версии, если еще вдруг актуально

@trueflywood забавно читать такие комментарии) Если что на гитлабе ПР может создать любой
