### ISSUE TITLE
Ошибка при Аот компиляции 

### ISSUE THREAD

**Issue by mlada** [FriOne/ng-yandex-metrika#3]
Версии 
@ angular/cli : "1.1.3", 
ts-node: "3.0.4"
node 6.11.1

При сборке (ng build --prod --aot=true) возникает ошибка 
"Unexpected token: name (YandexCounterConfig) " 

![1512032833649](https://user-images.githubusercontent.com/20365367/33422521-8ae803aa-d5e8-11e7-9b9b-3c9e579e6a5a.png)

**Comment by FriOne** [comment]
@mlada я не использую этот модуль сам, но постараюсь помочь.
Покажи какой конфиг используешь для модуля.
Еще неплохо бы то место, где `Unexpected token: name`

**Comment by mlada** [comment]
@FriOne О_о пофиксилось чудесным образом, не смогла воспроизвести ошибку )

**Comment by mlada** [comment]
@FriOne в metrika.config.d.ts 
`export declare class YandexCounterConfig implements CounterConfig {
    id: string | number;
    clickmap: boolean;
    trackLinks: boolean;
    accurateTrackBounce: boolean;
    webvisor: boolean;
    trackHash: boolean;
    ut: string;
}`

**Comment by FriOne** [comment]
@mlada в этом файле нет `name`. Скинь все таки как добавляешь модуль с конфигом.
Есть вероятность, что проблема в старой версии CLI

**Comment by mlada** [comment]
@FriOne это то, что надо?
![1512625596155](https://user-images.githubusercontent.com/20365367/33700614-dea5ec78-db4c-11e7-9e1c-d90f385e11d0.png)
![untitled-1](https://user-images.githubusercontent.com/20365367/33700615-decaff18-db4c-11e7-8d62-8c01d8942fe9.png)

**Comment by FriOne** [comment]
@mlada Да, все так, последнюю версию (0.4.0) попробовала?
Еще иvпортировать лучше просто 'ng-yandex-metrika'.

**Comment by mlada** [comment]
@FriOne Спасибо! собрался!!! =)
