### ISSUE TITLE
[Firefox] Cookie “_ym_isad” will be soon rejected because it has the “SameSite”

### ISSUE THREAD

**Issue by splincode** [FriOne/ng-yandex-metrika#39]
Cookie “_ym_isad” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

https://taiga-ui.dev/getting-started

Request to access cookie or storage on “<URL>)” was blocked because it came from a tracker and content blocking is enabled.

![image](https://user-images.githubusercontent.com/12021443/170298989-03bf263b-d1d1-4544-8901-f5fd1ed9318b.png)

**Comment by FriOne** [comment]
I am not from Yandex, so it is not the problem of this module.
