### ISSUE TITLE
message: 'Не удается найти имя "defaultCounter".'

### ISSUE THREAD

**Issue by Form1ca** [FriOne/ng-yandex-metrika#4]
severity: 'Ошибка'
message: 'Не удается найти имя "defaultCounter".'

**Comment by FriOne** [comment]
@Form1ca можно как-то поподробнее? Какая строка, что за строгость? Как используется?

**Comment by Form1ca** [comment]
@FriOne 
**Выполнил только эти шаги:**
npm install ng-yandex-metrika --save
Чтобы подключить, нужно добавить скрипт в шаблон, либо подключить с помощью загрузчика модулей, и подключить в приложение.

import { MetrikaModule } from 'ng-yandex-metrika';

@NgModule({
  imports: [
    MetrikaModule.forRoot(
      {id: 35567075, webvisor: true}, // CounterConfig | CounterConfig[]
      defaultCounter?: number | string // Можно задать ид счетчика, либо порядковый номер в массиве.
    ),
  ]
})

Как я понимаю, эта переменная (**defaultCounter**) должно быть где-то определeна

**Comment by FriOne** [comment]
@Form1ca видимо опыта совсем мало :)
`defaultCounter?: number | string`
`?: number | string` - ? значит, что параметр необязательный, число или строка.
Если счетчик один, то ничего не надо тут писать, просто первым параметром конфиг счетчика и все.
```typescript
@NgModule({
  imports: [
    MetrikaModule.forRoot({id: 35567075, webvisor: true}),
  ]
})
```
