### ISSUE TITLE
Angular 17 update

### ISSUE THREAD

**Issue by omqmo** [FriOne/ng-yandex-metrika#49]
Angular 17 update need.

**Comment by omqmo** [comment]
Очень надеюсь на обновление, так как из-за старой версии в облоках не работает npm ci

**Comment by FriOne** [comment]
@omqmo будет классно, если сделаете реквест.
Если обновлять, то надо переделать на сигналы скорее всего.
Давно не работал с ангуларом, но мб найду время на этой или следующей неделе.

**Comment by FriOne** [comment]
@omqmo обновил, попробуй 17 версию.

**Comment by omqmo** [comment]
@FriOne если в поекте используются angular-зависимости разных версий, то он просто не позволяет устанавливать какие-либо другие пакеты. Только с флагом --force, но он не совместим с командой `npm ci`.
