### ISSUE TITLE
Add support for Session Replay 2.0 using tag.js (Ya.Metrika2)

### ISSUE THREAD

**Issue by psmout** [FriOne/ng-yandex-metrika#5]
Hello,

Are you considering adding support for session replay 2.0?

Session Replay 2.0 counter code uses a new script tag.js - https://mc.yandex.ru/metrika/tag.js - and uses a different API (Ya.Metrika2)

Thanks for the great package so far, much better than using the counter code directly!
Peter

**Comment by FriOne** [comment]
@psmout Could you point to the documentation? Session replay 2.0 is the same as "Вебвизор 2.0". My account on yandex doesn't have possibility to enable it. I wrote to the support. Hope I will make it when they enable it for me.

**Comment by psmout** [comment]
Yes I think so, they use a thing called "webvisor" to play back the recorded sessions. Sorry I don't have any documentation links.

Session Replay 2.0 is still in beta but I was able to get access and enabled on my account by writing to them.

**Comment by FriOne** [comment]
Yeah, I wrote them too. If you want to, you could make PR here.

**Comment by FriOne** [comment]
Sorry, they denied my request. But maybe it is because I wrote to a wrong support :)
Where did you write them?

**Comment by FriOne** [comment]
They will give access tomorrow, I will try to make update as soon as possible.

**Comment by psmout** [comment]
Ok great to hear it. If you find any documentation or links I'd love to
read them! Thanks.

On 16 Jan. 2018 2:22 am, "Roman Lyubimov" <notifications@github.com> wrote:

They will give access tomorrow, I will try to make update as soon as
possible.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/FriOne/ng-yandex-metrika/issues/5#issuecomment-357729373>,
or mute the thread

**Comment by FriOne** [comment]
@psmout they didn't give the access. I don't know why, so we need to wait until it will be released.

**Comment by psmout** [comment]
@FriOne  I have requested they reconsider and give you access to the beta (after all, it was yandex support who told me I should ask you to add support for 2.0 in the first place!)

Here's hoping they reconsider their business decision.

**Comment by FriOne** [comment]
@psmout Great! Now I have it :)

**Comment by FriOne** [comment]
@psmout, will it make sense if I translate README to English? It may be useful for people who use metrika and don't know Russian. What do you think?

**Comment by psmout** [comment]
Yeah I think that might help the reach of the project if you can do that!

On 23 Jan. 2018 5:55 pm, "Roman Lyubimov" <notifications@github.com> wrote:

@psmout <https://github.com/psmout>, will it make sense if I translate
README to English? It may be useful for people who use metrika and don't
know Russian. What do you think?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/FriOne/ng-yandex-metrika/issues/5#issuecomment-359705891>,
or mute the thread

**Comment by psmout** [comment]
@FriOne Sorry for the delay, I have had a chance to test 2.0.1 and it appears to be working, I have some webvisor Session Replay 2.0 sessions appearing in the yandex metrika dashboard.

Thanks for your help, glad it was an easy fix!

**Comment by FriOne** [comment]
Great!
