### ISSUE TITLE
Can't build SSR with this lib: Property '"goalName"' is incompatible with index signature.

### ISSUE THREAD

**Issue by alexartwww** [FriOne/ng-yandex-metrika#56]
Error: node_modules/ng-yandex-metrika/lib/ng-yandex-metrika-goal.directive.d.ts:18:90 - error TS2344: Type '{ goalName: { alias: "goalName"; required: false; }; eventName: { alias: "eventName"; required: false; }; params: { alias: "params"; required: false; }; counterId: { alias: "counterId"; required: false; }; callback: { ...; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"goalName"' is incompatible with index signature.
    Type '{ alias: "goalName"; required: false; }' is not assignable to type 'string'.

18     static ɵdir: i0.ɵɵDirectiveDeclaration<MetrikaGoalDirective, "[metrikaGoal]", never, { "goalName": { "alias": "goalName"; "required": false; }; "eventName": { "alias": "eventName"; "required": false; }; "params": { "alias": "params"; "required": false; }; "counterId": { "alias": "counterId"; "required": false; }; "callback": { "alias": "callback"; "required": false; }; }, {}, never, never, true, never>;
                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Angular 15

**Comment by alexartwww** [comment]
I had to add "skipLibCheck": true, to ts config

**Comment by alexartwww** [comment]
main.9d49864e87aedbf8.js:1 ERROR TypeError: A is not iterable
    at Ni (main.9d49864e87aedbf8.js:1:301732)
    at n.runInitializers (main.9d49864e87aedbf8.js:1:931945)
    at main.9d49864e87aedbf8.js:1:942060
    at o7 (main.9d49864e87aedbf8.js:1:941871)
    at main.9d49864e87aedbf8.js:1:942014
    at J.invoke (polyfills.d91aee16cafe8ac1.js:1:7392)
    at Object.onInvoke (main.9d49864e87aedbf8.js:1:935659)
    at J.invoke (polyfills.d91aee16cafe8ac1.js:1:7331)
    at ce.run (polyfills.d91aee16cafe8ac1.js:1:2711)
    at c4.run (main.9d49864e87aedbf8.js:1:936280)

**Comment by alexartwww** [comment]
```
import { MetrikaModule } from 'ng-yandex-metrika';

@NgModule({
  imports: [
    MetrikaModule.forRoot([
      { id: 35567075, webvisor: true }, 
]// CounterConfig[]
    ),
  ]
})
```

example is wrong

**Comment by FriOne** [comment]
@alexartwww I am unsure if I want to dive into this, I am not working with Angular nowadays.
The repository version is working, but it uses 17th version of Angular.
What version of Angular do you use? Have you tried a lower version of this lib that matches your angular version?
