### ISSUE TITLE
Добавление счетчика

### ISSUE THREAD

**Issue by b7w** [FriOne/ng-yandex-metrika#8]
День добрый!

В readme указано следуюшее:

> Чтобы подключить, нужно добавить скрипт в шаблон, либо подключить с помощью загрузчика модулей, и подключить в приложение.

А потом приведен пример кода настройки с помощью загрузчика. А вот описания как сделать через шаблон нету.

Добавьте пожалуйста описание настройки через шаблон.

**Comment by FriOne** [comment]
Добрый, В смысле написать как импортировать скрипт в html'е?
Не уверен, что сделаю это, PR приветствуется)
Возникли какие-то сложности?

**Comment by b7w** [comment]
Да, сложности. 
Не очень понятно что за скрипт. Это то что предоставляет yandex для вставки в html?

**Comment by FriOne** [comment]
Нет, иначе смысла в этой модуле нет. Опиши плз свою проблему.
Я сам не использую этот модуль и в основном обновляю его, когда какие-то апдейты необходимы.
Описание библиотеки мигрировало с первой версии, думаю нет случая, когда нужно вставлять что-то в html. Буду признателен, если сделаешь ПР под это.
