### ISSUE TITLE
Не отправляются параметры визитов в yandex

### ISSUE THREAD

**Issue by mlada** [FriOne/ng-yandex-metrika#9]
При инициализации счетчика надо добавить отправку параметров.

Пример: 
<script type="text/javascript">
var yaParams = {'Логин': '[% вставка логина пользователя из шаблонизатора сайта %]' || 'Гость'};
var yaCounterXXXXXX = new Ya.Metrika({id: XXXXXX, 
**params: window.yaParams||{}});**
</script>

https://yandex.ua/support/metrika/code/counter-initialize.html#counter-initialize__counter_params
https://yandex.ua/support/metrika/reports/visit-params.html#visit-params

**Comment by FriOne** [comment]
Спасибо, Млада, ПР принят)
